#include "openclaw/gateway_client.hpp"
#include <boost/asio.hpp>
#include <boost/asio/ssl.hpp>
#include <boost/beast/core.hpp>
#include <boost/beast/ssl.hpp>
#include <boost/beast/websocket.hpp>
#include <atomic>
#include <chrono>
#include <random>
#include <stdexcept>
#include <thread>
namespace openclaw { namespace asio=boost::asio; namespace beast=boost::beast; namespace ws=beast::websocket; namespace ssl=asio::ssl; using tcp=asio::ip::tcp;
GatewayUrl parse_gateway_url(const std::string& u){GatewayUrl r;size_t p=0;if(u.rfind("wss://",0)==0){r.secure=true;p=6;r.port="443";}else if(u.rfind("ws://",0)==0){p=5;r.port="80";}else throw std::invalid_argument("gateway URL must start ws:// or wss://");auto slash=u.find('/',p), end=slash==std::string::npos?u.size():slash;auto hp=u.substr(p,end-p);if(hp.empty())throw std::invalid_argument("gateway URL has no host");if(hp.front()=='['){auto rb=hp.find(']');if(rb==std::string::npos)throw std::invalid_argument("invalid IPv6 host");r.host=hp.substr(1,rb-1);if(rb+1<hp.size()){if(hp[rb+1]!=':')throw std::invalid_argument("invalid gateway port");r.port=hp.substr(rb+2);}}else{auto c=hp.rfind(':');if(c!=std::string::npos&&hp.find(':')==c){r.host=hp.substr(0,c);r.port=hp.substr(c+1);}else r.host=hp;}if(r.host.empty()||r.port.empty())throw std::invalid_argument("invalid gateway URL");r.target=slash==std::string::npos?"/":u.substr(slash);return r;}
struct GatewayClient::Impl{GatewayUrl url;DeviceStore& store;std::string bootstrap;asio::io_context ioc;ssl::context tls{ssl::context::tls_client};std::unique_ptr<ws::stream<beast::tcp_stream>> plain;std::unique_ptr<ws::stream<beast::ssl_stream<beast::tcp_stream>>> secure;std::atomic<unsigned long long> ids{1};bool ready=false;SequenceTracker seq;bool needsRecovery=false;Impl(std::string u,DeviceStore&s,std::string b):url(parse_gateway_url(u)),store(s),bootstrap(std::move(b)){tls.set_default_verify_paths();tls.set_verify_mode(ssl::verify_peer);}std::string id(const char* p){return std::string(p)+"-"+std::to_string(ids++);}void write(const std::string&s){if(secure)secure->write(asio::buffer(s));else if(plain)plain->write(asio::buffer(s));else throw std::runtime_error("gateway not connected");}std::string read(){beast::flat_buffer b;if(secure)secure->read(b);else if(plain)plain->read(b);else throw std::runtime_error("gateway not connected");return beast::buffers_to_string(b.data());}void transport(){tcp::resolver resolver(ioc);auto ep=resolver.resolve(url.host,url.port);if(url.secure){secure=std::make_unique<ws::stream<beast::ssl_stream<beast::tcp_stream>>>(ioc,tls);if(!SSL_set_tlsext_host_name(secure->next_layer().native_handle(),url.host.c_str()))throw std::runtime_error("TLS SNI setup failed");beast::get_lowest_layer(*secure).connect(ep);secure->next_layer().handshake(ssl::stream_base::client);secure->handshake(url.host,url.target);}else{plain=std::make_unique<ws::stream<beast::tcp_stream>>(ioc);beast::get_lowest_layer(*plain).connect(ep);plain->handshake(url.host,url.target);}}};
GatewayClient::GatewayClient(std::string u,DeviceStore&s,std::string b):p_(new Impl(std::move(u),s,std::move(b))){}GatewayClient::~GatewayClient(){try{close();}catch(...){}}
bool GatewayClient::connected()const{return p_->ready;}void GatewayClient::close(){p_->ready=false;beast::error_code ec;if(p_->secure)p_->secure->close(ws::close_code::normal,ec);if(p_->plain)p_->plain->close(ws::close_code::normal,ec);p_->secure.reset();p_->plain.reset();}
ConnectResult GatewayClient::connect(std::chrono::milliseconds){try{close();p_->transport();auto first=p_->read();auto ch=GatewayProtocol::challenge(first);if(!ch)return {ConnectResult::State::Failed,"","Gateway did not send a valid connect.challenge"};auto d=p_->store.load_or_create_identity();auto saved=p_->store.load_token();std::string token=saved?saved->token:p_->bootstrap;std::vector<std::string> scopes={"operator.read","operator.write","operator.approvals"};auto payload=build_device_auth_payload_v3(d,"cli","cli","operator",scopes,ch->ts,token,ch->nonce,"cli","desktop");auto sig=sign_device_payload(d,payload);auto rid=p_->id("connect");p_->write(GatewayProtocol::connect(rid,token,"cli",device_json(d,sig,ch->ts,ch->nonce)));for(;;){auto raw=p_->read();auto f=GatewayProtocol::parse(raw);if(f.kind==Frame::Kind::Event)continue;if(f.id!=rid)continue;if(!f.ok){auto pr=parse_pairing_required(raw);if(pr){close();return {ConnectResult::State::PairingRequired,pr->requestId,pr->recommendedNextStep};}close();return {ConnectResult::State::Failed,"",f.error.empty()?raw:f.error};}if(auto t=parse_hello_device_token(raw))p_->store.store_token(*t);p_->seq.reset_connection();p_->needsRecovery=false;p_->ready=true;return {ConnectResult::State::Connected,"","connected"};}}catch(const std::exception&e){close();return {ConnectResult::State::Failed,"",e.what()};}}
std::string GatewayClient::call(const std::string&m,const std::string&params,std::chrono::milliseconds){if(!p_->ready)throw std::runtime_error("gateway not connected");auto rid=p_->id("rpc");p_->write(GatewayProtocol::request(rid,m,params));for(;;){auto raw=p_->read();auto f=GatewayProtocol::parse(raw);if(f.kind==Frame::Kind::Response&&f.id==rid){if(!f.ok)throw std::runtime_error(f.error.empty()?raw:f.error);return f.payload;}/* events are intentionally skipped in synchronous call; use pump for streaming */}}
static std::string idem(){static std::atomic<unsigned long long> n{1};return "ocm-"+std::to_string(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count())+"-"+std::to_string(n++);}
std::string GatewayClient::send_chat(const std::string&key,const std::string&msg,const std::string&sid,const std::string&attachments){if(!p_->ready)throw std::runtime_error("gateway not connected");auto rid=p_->id("chat");p_->write(GatewayProtocol::chat_send(rid,key,msg,idem(),sid,attachments));for(;;){auto raw=p_->read();auto f=GatewayProtocol::parse(raw);if(f.kind==Frame::Kind::Response&&f.id==rid){if(!f.ok)throw std::runtime_error(f.error.empty()?raw:f.error);return f.payload;}}}
std::string GatewayClient::abort_chat(const std::string&key,const std::string&run){return call("chat.abort",run.empty()?"{\"sessionKey\":\""+GatewayProtocol::escape(key)+"\"}":"{\"sessionKey\":\""+GatewayProtocol::escape(key)+"\",\"runId\":\""+GatewayProtocol::escape(run)+"\"}");}
HydrationResult GatewayClient::hydrate(const std::string& key,int historyLimit){if(!p_->ready)throw std::runtime_error("gateway not connected");HydrationResult h;h.sessions=call("sessions.subscribe","{\"limit\":60,\"ownerFirst\":true}");h.subscribed=true;if(!key.empty()){call("sessions.messages.subscribe","{\"sessionKey\":\""+GatewayProtocol::escape(key)+"\"}");h.history=call("chat.history","{\"sessionKey\":\""+GatewayProtocol::escape(key)+"\",\"limit\":"+std::to_string(historyLimit)+"}");}p_->needsRecovery=false;return h;}
ConnectResult GatewayClient::reconnect(const std::string& key,int maxAttempts){ReconnectPolicy policy;ConnectResult r;for(int i=0;i<maxAttempts;++i){r=connect();if(r.state==ConnectResult::State::Connected){if(!key.empty())try{hydrate(key);}catch(const std::exception&e){close();r={ConnectResult::State::Failed,"",std::string("reconnected but hydration failed: ")+e.what()};}else p_->needsRecovery=false;if(r.state==ConnectResult::State::Connected)return r;}if(r.state==ConnectResult::State::PairingRequired)return r;std::this_thread::sleep_for(std::chrono::milliseconds(policy.next_delay_ms()));}return r;}
bool GatewayClient::recovery_needed()const{return p_->needsRecovery;}void GatewayClient::clear_recovery_needed(){p_->needsRecovery=false;}
void GatewayClient::pump(const EventHandler& cb,std::chrono::milliseconds duration){if(!p_->ready)return;auto until=std::chrono::steady_clock::now()+duration;while(std::chrono::steady_clock::now()<until){beast::error_code ec;auto& sock=p_->secure?beast::get_lowest_layer(*p_->secure).socket():beast::get_lowest_layer(*p_->plain).socket();auto avail=sock.available(ec);if(ec){p_->ready=false;p_->needsRecovery=true;return;}if(!avail){std::this_thread::sleep_for(std::chrono::milliseconds(20));continue;}try{auto raw=p_->read();auto f=GatewayProtocol::parse(raw);if(f.kind==Frame::Kind::Event){auto d=p_->seq.observe(f);if(d.gap)p_->needsRecovery=true;if(d.accept)cb(f,raw);}}catch(...){p_->ready=false;p_->needsRecovery=true;return;}}}
}
