package ai.openclaw.mobile

import android.content.Context
import android.os.Handler
import android.os.Looper
import android.util.Base64
import okhttp3.*
import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID

class GatewayClient(context:Context,private val url:String,private val bootstrapToken:String,private val listener:(JSONObject)->Unit){
 private val http=OkHttpClient();private var ws:WebSocket?=null;private val store=DeviceIdentityStore(context);private var connectId:String?=null;private var selectedSession="main";private var lastSeq:Long?=null;private var reconnectAttempt=0;private var closing=false;private val handler=Handler(Looper.getMainLooper());private val pending=mutableMapOf<String,String>()
 private val scopes=listOf("operator.read","operator.write","operator.approvals");var connected=false;private set;var activeRunId:String?=null;private set;var maxAttachmentBytes:Long?=null;private set;var maxImageBytes:Long?=null;private set;var maxPayloadBytes:Long?=null;private set
 fun connect(){closing=false;connected=false;listener(JSONObject().put("type","connection-state").put("state","connecting"));ws=http.newWebSocket(Request.Builder().url(url).build(),object:WebSocketListener(){
  override fun onMessage(webSocket:WebSocket,text:String){val j=JSONObject(text);if(j.optString("type")=="event"&&j.has("seq")){val n=j.optLong("seq");val prev=lastSeq;if(prev!=null&&n>prev+1){listener(JSONObject().put("type","sequence-gap").put("expected",prev+1).put("received",n));hydrate()};if(prev!=null&&n<=prev)return;lastSeq=n};handle(j);listener(j)}
  override fun onFailure(webSocket:WebSocket,t:Throwable,response:Response?){connected=false;listener(JSONObject().put("type","local-error").put("error",t.message?:"WebSocket failure"));scheduleReconnect()}
  override fun onClosed(webSocket:WebSocket,code:Int,reason:String){connected=false;if(!closing)scheduleReconnect()}
 })}
 private fun handle(j:JSONObject){
  if(j.optString("type")=="event"&&j.optString("event")=="connect.challenge"){val p=j.optJSONObject("payload")?:return;val nonce=p.optString("nonce");if(nonce.isBlank()||!p.has("ts")||p.optLong("ts",-1)<0){listener(JSONObject().put("type","local-error").put("error","Invalid connect.challenge"));return};sendConnect(nonce,p.getLong("ts"));return}
  if(j.optString("type")=="res"&&j.optString("id")==connectId){if(j.optBoolean("ok")){connected=true;reconnectAttempt=0;lastSeq=null;val payload=j.optJSONObject("payload");val auth=payload?.optJSONObject("auth");val dt=auth?.optString("deviceToken").orEmpty();if(dt.isNotBlank()){val a=auth!!.optJSONArray("scopes");val ss=mutableSetOf<String>();if(a!=null)for(i in 0 until a.length())ss+=a.getString(i);store.saveToken(dt,auth.optString("role","operator"),ss)};val policy=payload?.optJSONObject("policy");maxPayloadBytes=policy?.optLongOrNull("maxPayload");val att=policy?.optJSONObject("attachments");maxAttachmentBytes=att?.optLongOrNull("maxBytes");maxImageBytes=att?.optLongOrNull("maxImageBytes");listener(JSONObject().put("type","connection-state").put("state","connected"));hydrate()}else{val e=j.optJSONObject("error");if(e?.optString("code")=="PAIRING_REQUIRED"){connected=false;val d=e.optJSONObject("details");listener(JSONObject().put("type","pairing-required").put("requestId",d?.optString("requestId").orEmpty()).put("recommendedNextStep",d?.optString("recommendedNextStep").orEmpty()))}};return}
  if(j.optString("type")=="res"){val id=j.optString("id");val method=pending.remove(id);if(method=="chat.send"&&j.optBoolean("ok")){val p=j.optJSONObject("payload");activeRunId=p?.optString("runId")?.takeIf{it.isNotBlank()}?:p?.optString("id")?.takeIf{it.isNotBlank()};listener(JSONObject().put("type","run-state").put("state","running").put("runId",activeRunId?:""))}else if(method=="chat.abort"&&j.optBoolean("ok")){activeRunId=null;listener(JSONObject().put("type","run-state").put("state","paused"))}else if(method=="chat.history"&&j.optBoolean("ok")){listener(JSONObject().put("type","history-result").put("payload",j.opt("payload")))}else if((method=="sessions.subscribe"||method=="sessions.list")&&j.optBoolean("ok")){listener(JSONObject().put("type","sessions-result").put("payload",j.opt("payload")))}
  }
  if(j.optString("type")=="event"){val ev=j.optString("event");if(ev=="agent"||ev=="chat"||ev=="session.message"){val p=j.optJSONObject("payload")?:JSONObject();val phase=p.optString("phase",p.optString("lifecycle"));val run=p.optString("runId");if(run.isNotBlank())activeRunId=run;val delta=extractText(p);if(delta.isNotBlank())listener(JSONObject().put("type","assistant-delta").put("text",delta).put("runId",run));if(phase in setOf("end","final","done","completed","aborted","error")){activeRunId=null;listener(JSONObject().put("type","run-state").put("state",phase.ifBlank{"done"}))}}
  }
 }
 private fun sendConnect(nonce:String,signedAt:Long){val identity=store.identity();val saved=store.token();val authToken=saved?.token?:bootstrapToken;val platform="android";val family="mobile";val payload=listOf("v3",identity.id,"cli","cli","operator",scopes.joinToString(","),signedAt.toString(),authToken,nonce,platform,family).joinToString("|");val device=JSONObject().put("id",identity.id).put("publicKey",identity.publicKey).put("signature",store.sign(identity,payload)).put("signedAt",signedAt).put("nonce",nonce);val p=JSONObject().put("minProtocol",4).put("maxProtocol",4).put("client",JSONObject().put("id","cli").put("version","0.7.0-dev").put("platform",platform).put("deviceFamily",family).put("mode","cli")).put("role","operator").put("scopes",JSONArray(scopes)).put("caps",JSONArray()).put("commands",JSONArray()).put("permissions",JSONObject()).put("auth",JSONObject().put("token",authToken).apply{if(saved!=null)put("deviceToken",saved.token)}).put("locale","en-US").put("userAgent","openclaw-mobile-android/0.7.0-dev");connectId=request("connect",p,device)}
 private fun request(method:String,params:JSONObject,device:JSONObject?=null):String{val id=UUID.randomUUID().toString();if(device!=null)params.put("device",device);pending[id]=method;ws?.send(JSONObject().put("type","req").put("id",id).put("method",method).put("params",params).toString());return id}
 fun request(method:String,params:JSONObject=JSONObject())=request(method,params,null)
 private fun scheduleReconnect(){if(closing)return;val delay=(500L shl reconnectAttempt.coerceAtMost(6)).coerceAtMost(30000L);reconnectAttempt++;listener(JSONObject().put("type","connection-state").put("state","reconnecting").put("delayMs",delay));handler.postDelayed({if(!closing)connect()},delay)}
 fun selectSession(key:String){selectedSession=key;hydrate()}
 fun hydrate(){sessions();request("sessions.messages.subscribe",JSONObject().put("sessionKey",selectedSession));request("chat.history",JSONObject().put("sessionKey",selectedSession).put("limit",200))}
 fun health()=request("health");fun sessions()=request("sessions.subscribe",JSONObject().put("limit",100).put("ownerFirst",true))
 fun sendChat(sessionKey:String,message:String,attachments:List<AttachmentDraft> = emptyList()):String{selectedSession=sessionKey;val p=JSONObject().put("sessionKey",sessionKey).put("message",message).put("idempotencyKey",UUID.randomUUID().toString());if(attachments.isNotEmpty()){val a=JSONArray();attachments.forEach{f->a.put(JSONObject().put("type","file").put("mimeType",f.mimeType).put("fileName",f.name).put("content",Base64.encodeToString(f.bytes,Base64.NO_WRAP)))};p.put("attachments",a)};return request("chat.send",p)}
 fun pauseOrStop():String{val p=JSONObject().put("sessionKey",selectedSession);activeRunId?.let{p.put("runId",it)};return request("chat.abort",p)}
 fun resume():String=sendChat(selectedSession,"Continue from where you left off.")
 fun close(){closing=true;connected=false;handler.removeCallbacksAndMessages(null);ws?.close(1000,"bye");http.dispatcher.executorService.shutdown()}
 private fun extractText(p:JSONObject):String{listOf("delta","text","content").forEach{k->val v=p.opt(k);if(v is String&&v.isNotBlank())return v};val m=p.optJSONObject("message");if(m!=null){val t=m.optString("text");if(t.isNotBlank())return t;val c=m.opt("content");if(c is String)return c;if(c is JSONArray){val b=StringBuilder();for(i in 0 until c.length()){val x=c.optJSONObject(i)?:continue;if(x.optString("type") in listOf("text","output_text"))b.append(x.optString("text"))};return b.toString()}};return ""}
 private fun JSONObject.optLongOrNull(key:String):Long? = if(has(key)&&!isNull(key))optLong(key) else null
}
